# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_mt_cpp <- function(Y, X, beta, gamma) {
    .Call(`_pastasales_get_mt_cpp`, Y, X, beta, gamma)
}

get_mt_grad_cpp <- function(Y, X, beta, gamma) {
    .Call(`_pastasales_get_mt_grad_cpp`, Y, X, beta, gamma)
}

loglik_cpp <- function(Y, X, beta, gamma) {
    .Call(`_pastasales_loglik_cpp`, Y, X, beta, gamma)
}

loglik_grad_cpp <- function(Y, X, beta, gamma) {
    .Call(`_pastasales_loglik_grad_cpp`, Y, X, beta, gamma)
}

proj_beta_cpp <- function(beta, epsilon = 1e-4) {
    .Call(`_pastasales_proj_beta_cpp`, beta, epsilon)
}

bfgs_cpp <- function(Y, X, beta0, gamma0, maxIter = 100L, tol = 1e-5, verbose = FALSE) {
    .Call(`_pastasales_bfgs_cpp`, Y, X, beta0, gamma0, maxIter, tol, verbose)
}

bfgs_cpp2 <- function(Y, X, beta0, gamma0, maxIter = 100L, tol = 1e-5, verbose = FALSE) {
    .Call(`_pastasales_bfgs_cpp2`, Y, X, beta0, gamma0, maxIter, tol, verbose)
}

proj_grad_descent_cpp <- function(Y, X, beta0, gamma0, lr = 1e-4, maxIter = 100L, tol = 1e-5, return_allIters = FALSE, verbose = FALSE) {
    .Call(`_pastasales_proj_grad_descent_cpp`, Y, X, beta0, gamma0, lr, maxIter, tol, return_allIters, verbose)
}

