# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dnorm_vec_cpp <- function(x, mu, sigsq, log = TRUE) {
    .Call(`_pastasales_dnorm_vec_cpp`, x, mu, sigsq, log)
}

rdirichlet_cpp <- function(alpha_m) {
    .Call(`_pastasales_rdirichlet_cpp`, alpha_m)
}

ddirichlet_cpp <- function(x, alpha, log) {
    .Call(`_pastasales_ddirichlet_cpp`, x, alpha, log)
}

get_fit_par_cpp <- function(Y, X, beta, gamma) {
    .Call(`_pastasales_get_fit_par_cpp`, Y, X, beta, gamma)
}

loglik_par_cpp <- function(Y, X, beta, gamma) {
    .Call(`_pastasales_loglik_par_cpp`, Y, X, beta, gamma)
}

run_mcmc_par_cpp <- function(Y, X, q = 5L, n_iter = 1000L, hyperparams = NULL, proposal_sd = 0.05, verbose = FALSE) {
    .Call(`_pastasales_run_mcmc_par_cpp`, Y, X, q, n_iter, hyperparams, proposal_sd, verbose)
}

get_mt_cpp <- function(Y, X, beta, gamma) {
    .Call(`_pastasales_get_mt_cpp`, Y, X, beta, gamma)
}

get_mt_grad_cpp <- function(Y, X, beta, gamma) {
    .Call(`_pastasales_get_mt_grad_cpp`, Y, X, beta, gamma)
}

loglik_cpp <- function(Y, X, beta, gamma) {
    .Call(`_pastasales_loglik_cpp`, Y, X, beta, gamma)
}

loglik_grad_cpp <- function(Y, X, beta, gamma) {
    .Call(`_pastasales_loglik_grad_cpp`, Y, X, beta, gamma)
}

proj_beta_cpp <- function(beta, epsilon = 1e-4) {
    .Call(`_pastasales_proj_beta_cpp`, beta, epsilon)
}

proj_grad_descent_cpp <- function(Y, X, beta0, gamma0, lr = 1e-4, maxIter = 100L, tol = 1e-5, return_allIters = FALSE, verbose = FALSE) {
    .Call(`_pastasales_proj_grad_descent_cpp`, Y, X, beta0, gamma0, lr, maxIter, tol, return_allIters, verbose)
}

